name: Check markdown files

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './markdown_check/go.mod'

    - name: Build
      run: go build -C markdown_check/ -v -o ../md_check

    - name: Test
      run: go test -C markdown_check/ -v
